# Generated by Django 5.0.3 on 2024-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='duration',
        ),
        migrations.AlterField(
            model_name='display',
            name='update_interval',
            field=models.PositiveIntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], default=10, help_text='Number of seconds each slide is displayed.'),
        ),
    ]
