# Generated by Django 5.0.3 on 2024-04-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_remove_slide_duration_alter_display_update_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='duration',
            field=models.PositiveIntegerField(choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60)], default=10, help_text='Number of seconds the slide is displayed.'),
        ),
    ]
